# programs
---
# blogs
* https://blogs.securiteam.com/index.php/archives/3445
* https://medium.com/@HassanYusufzai/device-authorization-bypass-aa508c9193ed
* http://blog.bugcrowd.com/what-we-can-learn-from-netgears-approach-to-security
* https://bugcrowd.com/netgear
* http://blog.bugcrowd.com/introducing-the-bugcrowd-researcher-advisory-council
* https://ret2got.wordpress.com/2017/10/05/how-i-could-have-mass-uploaded-from-every-flickr-account
* https://www.contextis.com/blog/xslt-server-side-injection-attacks
* https://www.hackerone.com/blog/node-js-foundation
* https://www.hackerone.com/blog/hacker-powered-security-report-retail-edition
* https://blogs.securiteam.com/index.php/archives/3444
* https://blogs.securiteam.com/index.php/archives/3454
* http://blog.blackfan.ru/2017/09/devtwittercom-xss.html
* https://labs.detectify.com/2017/09/26/trackmania-a-chrome-plugin-to-stalk-your-friends
* https://www.hackerone.com/blog/marten-mickos-tripwire-interview
* https://www.hackerone.com/q-and-a-with-hacker-gerban-javado
* http://blake12356.com/interviews/2017/09/21/Interview-with-Sam-Houston.html
* https://philippeharewood.com/disclose-users-with-roles-on-facebook-pages
* http://blog.bugcrowd.com/cut-through-the-noise-the-value-of-a-disclosure-program
* https://www.hackerone.com/blog/How-The-US-Government-is-Out-Innovating-Corporate-America
* https://medium.com/@th3g3nt3l/900-xss-in-yahoo-recon-wins-65ee6d4bfcbd?source=rss-e93a8f4034a8------2
* https://blogs.securiteam.com/index.php/archives/3411
* https://blogs.securiteam.com/index.php/archives/3386
* https://medium.com/@vipinxsec/how-i-bypassed-practos-firewall-and-triggered-a-xss-b30164a8f1dc
* https://www.bugcrowd.com
* http://blog.bugcrowd.com/bugcrowd-correcting-the-math-for-customers-in-their-cybersecurity-equation
* https://www.hackerone.com/blog/more-than-just-security-451-research-webinar-recap
* https://twitter.com/uraniumhacker/status/910981945214959616
* https://medium.com/@intideceukelaire/how-i-hacked-hundreds-of-companies-through-their-helpdesk-b7680ddc2d4c
* http://www.shawarkhan.com/2017/09/exploiting-multiple-self-xsses-via.html?m=1
* https://www.hackerone.com/blog/shopify-shares-how-hackers-help-secure-40B-in-transactions
* http://guptashubham.com/all-about-hackerone-private-program-terapeak
* https://medium.com/@aneeskhan/how-i-bypassed-open-redirection-tokens-using-http-parameter-pollution-ea5be084a0f4
* https://securedrop.org
* http://blog.bugcrowd.com/ethical-security-research-on-securedrop
* http://samidrif.net/index.php/2017/08/29/yo-github-could-you-find-something-for-me
* http://www.ansariosama.com/2017/09/exploiting-single-request-for-multiple.html
* http://bugdiscloseguys.com/blog/index.php/2017/09/18/7
* http://blog.bugcrowd.com/moving-fast-with-security
* https://ibotta.com
* https://blog.avuln.com/article/4
* https://blogs.securiteam.com/index.php/archives/3414
* https://medium.com/@armaanpathan/stealing-user-details-by-exploiting-cors-c5ee86ebe7fb
* https://www.dwheeler.com/secure-programs/Secure-Programs-HOWTO/index.html
* https://bugbaba.blogspot.in/2017/09/two-factor-authentication-bypass.html
* https://www.sjoerdlangkemper.nl/2016/09/28/attacking-jwt-authentication
* https://blog.netspi.com/playing-content-type-xxe-json-endpoints
* https://opnsec.com/2017/09/advanced-flash-vulnerabilities-in-youtube-part-4
* https://blogs.depotsec.com/write-ups/escape-from-self-xss
* https://www.synack.com/2017/09/11/swap
* https://medium.com/@xgeoffellis/ellis-geoff-v-smith-simon-legal-matters-9799719ffc5e
---
# tools
* https://gist.github.com/streaak/270bc07a395111d3b2f4bfa4f09162bb
* https://twitter.com/_devalias/status/915048540258234368
* http://scans.io
* https://justgetflux.com
* http://forked.yannick.io
* https://twitter.com/Jhaddix/status/913537538731556864
* https://edoverflow.com/2017/broken-link-hijacking
* http://www.irongeek.com/i.php?page=videos/derbycon7/s19-python-static-analysis-spencer-j-mcintyre
* https://edoverflow.com/2017/github-for-bugbountyhunters
* https://www.nccgroup.trust/uk/about-us/newsroom-and-events/blog/2017/september/decoder-improved-burp-suite-plugin-release-part-1
* https://edoverflow.com/2017/github-recon
* http://bugbountyworld.com/other/keywords.txt
* https://www.youtube.com/watch?v=tsRTf4q5u24
* https://twitter.com/Jhaddix/status/905581641493389312
* https://www.codeword.xyz/2015/09/02/three-ways-to-script-processes-in-parallel
* https://twitter.com/uraniumhacker/status/905626917927174144
* https://ifttt.com/applets/cpnKJ8ty-xsshunter-sms-trigger
* https://hackerone.com/lazy
---
# help
---
# news
---
# ctf
* https://twitter.com/HivarekarPranav/status/886798635576545281
* http://blog.bugcrowd.com/car-hacking-in-the-cloud-for-cheap-at-def-con
---
